name: build-and-push

on:
  push:
    branches: [ "main" ]
    # We accept any tag here and validate semver inside the job
    tags: [ "*" ]

permissions:
  contents: read
  packages: write   # needed to push to ghcr with GITHUB_TOKEN

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    env:
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute env (user/repo lowercased) and VERSION
        id: meta
        shell: bash
        run: |
          # Lowercased owner/repo
          OWNER_LOWER="${GITHUB_REPOSITORY_OWNER,,}"
          REPO_LOWER="${GITHUB_REPOSITORY##*/}"
          REPO_LOWER="${REPO_LOWER,,}"

          # If this is a tag, use it as VERSION, otherwise NIGHTLY.<timestamp>
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            # RFC3339 seconds, then replace spaces/:/+ with -
            VERSION="NIGHTLY.$(date --rfc-3339=seconds | sed 's/[ :+]/-/g')"
          fi

          echo "owner=${OWNER_LOWER}" >> "$GITHUB_OUTPUT"
          echo "repo=${REPO_LOWER}"  >> "$GITHUB_OUTPUT"
          echo "version=${VERSION}"  >> "$GITHUB_OUTPUT"

          # Write version.txt exactly like CircleCI
          echo "${VERSION}" > version.txt

      - name: If tag, ensure it looks like SemVer (vX.Y.Z or X.Y.Z with optional pre/build)
        if: ${{ github.ref_type == 'tag' }}
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          # tolerant semver: optional v- or V- prefix, 3 numbers, optional -prerelease and +build
          if [[ "$TAG" =~ ^[vV]?[0-9]+(\.[0-9]+){2}([-][0-9A-Za-z.-]+)?([+][0-9A-Za-z.-]+)?$ ]]; then
            echo "Tag $TAG accepted as semver."
          else
            echo "Tag $TAG is not a valid semver; refusing to publish." >&2
            exit 1
          fi

      - name: Login to GHCR (GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Optional: set up Buildx (build-push-action will create a builder implicitly;
      # uncomment if you need custom features)
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # ghcr.io/<owner>/<repo>:<version>
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.version }}
          # For ARM runner, default platform is linux/arm64; you can force it:
          # platforms: linux/arm64

      - name: Print digest
        run: |
          echo "Digest is: ${{ steps.build.outputs.digest }}"
